# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1608310569a02dc6601f58bf74afe31dc534abffc2f01e791dc3acb0abeabeb15bbc1cd9883701a5b32e566c5b8057d7c858dc0235a8381ad271dd5db06b7b8

test:
  secret_key_base: c5763a23c3ed714e52dc504682733f47cad32220a3727c26ededf7e048b1b00e9f83a0ede3d815ff9bd1be48ff9522cab8eb8a6a0430849c4d647005ced32d2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
